#!/usr/bin/env bash
# Assemble Cursor handoff prompt from .dorkpipe/self-analysis/* (facts only + structured guidance).
# Optional: DORKPIPE_SELF_ANALYSIS_USE_OLLAMA=1 DORKPIPE_SELF_ANALYSIS_MODEL=llama3.2
set -euo pipefail
ROOT="${DOCKPIPE_WORKDIR:-$(pwd)}"
ROOT="$(cd "$ROOT" && pwd)"
OUT="$ROOT/.dorkpipe/self-analysis"
DEST="$ROOT/.dockpipe/orchestrator-cursor-prompt.md"
mkdir -p "$ROOT/.dockpipe"

if [[ ! -d "$OUT" ]]; then
	echo "build-cursor-handoff: missing $OUT — run self-analysis-prep.sh and self-analysis-signals.sh first" >&2
	exit 1
fi

GO_N=$(cat "$ROOT/.dorkpipe/self-analysis/dorkpipe_go_files.count" 2>/dev/null || echo 0)
SPEC="$ROOT/.staging/workflows/dorkpipe-orchestrator/spec.example.yaml"
HAS_VERIFIER=0
if [[ -f "$SPEC" ]] && grep -q 'kind:.*verifier' "$SPEC"; then
	HAS_VERIFIER=1
fi
HAS_BRANCH=0
if [[ -f "$ROOT/src/lib/dorkpipe/examples/full-bar.yaml" ]]; then
	HAS_BRANCH=1
fi

{
	cat <<'EOF'
# Cursor implementation handoff — DockPipe + DorkPipe orchestration

This document was generated by **DockPipe’s self-analysis workflow** from **real repository scans** (file lists, ripgrep/grep hits, git metadata). Treat unchecked items as hypotheses to validate in code review.

EOF

	echo "## 1. Objective"
	cat <<'EOF'
Advance **DockPipe** (workflow execution fabric) and **DorkPipe** (`lib/dorkpipe/`, `bin/dorkpipe`) toward stronger **orchestrated reasoning**: multi-signal confidence, conditional retrieval/work, independent verifiers, bounded branch competition, evaluation (`dorkpipe eval`), and promotion of reusable assets — **without** replacing DockPipe’s core primitive or inventing a second engine.

EOF

	echo "## 2. Current state summary (from this checkout)"
	echo "- **Go files in \`lib/dorkpipe\`**: ${GO_N}"
	echo "- **Git HEAD / branch** (see \`.dockpipe/self-analysis/git.txt\` for full):"
	head -3 "$OUT/git.txt" 2>/dev/null | sed 's/^/  /' || true
	echo "- **DorkPipe packages (file counts)**:"
	if [[ -f "$OUT/dorkpipe_packages.tsv" ]]; then
		sed 's/^/  /' "$OUT/dorkpipe_packages.tsv"
	fi
	echo "- **Workflow configs present**:"
	if [[ -f "$OUT/workflow_configs.txt" ]]; then
		sed 's/^/  /' "$OUT/workflow_configs.txt"
	fi
	echo "- **Recent commits**:"
	if [[ -f "$OUT/signals_git_log.txt" ]]; then
		sed 's/^/  /' "$OUT/signals_git_log.txt"
	fi
	echo ""

	echo "## 3. Highest-value opportunities (grounded + strategic)"
	echo "The following are **actionable** directions consistent with \`AGENTS.md\` (primitive core, templates as extension):"
	echo ""
	if [[ "$HAS_VERIFIER" -eq 0 ]]; then
		echo "- **Independent verifier in the default orchestrator spec** (\`.staging/workflows/dorkpipe-orchestrator/spec.example.yaml\`): add a \`kind: verifier\` node after local LLM output so \`Vector.Verifier\` is populated before escalation (implementation in \`lib/dorkpipe/workers/workers.go\`, \`parseVerifierScore\`)."
	fi
	echo "- **Surface engine features in shipped examples**: \`lib/dorkpipe/examples/full-bar.yaml\` demonstrates \`branch_judge\`, \`retrieve_if_calibrated_below\`, and skips — mirror one pattern into \`spec.example.yaml\` so dogfood exercises the same code paths operators will rely on."
	echo "- **Metrics loop**: standardize \`bin/dorkpipe eval\` / \`promote\` after CI or nightly runs; extend \`.dorkpipe/metrics.jsonl\` consumers if new dimensions are added (\`lib/dorkpipe/engine/provenance.go\`)."
	echo "- **Asset promotion**: scripts under \`templates/core/bundles/dorkpipe/\` should stay referenced from workflows/docs when they become part of a supported path (collect/merge/verify-*)."
	echo "- **TODO/FIXME triage**: review hits in \`.dockpipe/self-analysis/signals_todo.txt\`; convert stable items into issues or small PRs."
	if [[ -f "$ROOT/.dorkpipe/metrics.jsonl" ]] && [[ -f "$OUT/signals_metrics_tail.txt" ]]; then
		echo "- **Existing \`.dorkpipe/metrics.jsonl\`**: tail captured in \`.dockpipe/self-analysis/signals_metrics_tail.txt\` — use for escalation / early-stop rates."
	fi
	echo ""
	echo "### Search hits (files touching orchestration keywords)"
	if [[ -f "$OUT/signals_engine_files.txt" ]]; then
		sed 's/^/  /' "$OUT/signals_engine_files.txt"
	fi
	echo ""

	echo "## 4. Exact files/modules to inspect"
	echo "| Area | Path |"
	echo "|------|------|"
	echo "| Engine / run loop | \`lib/dorkpipe/engine/run.go\`, \`lib/dorkpipe/engine/provenance.go\`, \`lib/dorkpipe/engine/branch.go\`, \`lib/dorkpipe/engine/parallel.go\` |"
	echo "| Spec / policy | \`lib/dorkpipe/spec/spec.go\` |"
	echo "| Workers | \`lib/dorkpipe/workers/workers.go\` |"
	echo "| Aggregation | \`lib/dorkpipe/aggregator/merge.go\` |"
	echo "| CLI | \`src/cmd/dorkpipe/main.go\` |"
	echo "| Eval / promotion | \`lib/dorkpipe/eval/eval.go\`, \`lib/dorkpipe/promotion/promotion.go\` |"
	echo "| DockPipe workflow (this integration) | \`.staging/workflows/dorkpipe-self-analysis/\` |"
	echo "| Orchestrator example DAG | \`.staging/workflows/dorkpipe-orchestrator/spec.example.yaml\` |"
	echo ""
	if [[ -f "$OUT/key_file_wc.txt" ]]; then
		echo "### Line counts (signal for complexity hotspots)"
		sed 's/^/  /' "$OUT/key_file_wc.txt"
		echo ""
	fi

	echo "## 5. Constraints / architecture rules (non-negotiable)"
	echo "- **DockPipe core** stays the single execution fabric: workflows, runtimes, resolvers, strategies, assets (\`AGENTS.md\`)."
	echo "- **No** vendor-specific logic in \`src/lib/dockpipe/application\` / runner for this work."
	echo "- **DorkPipe** composes via real \`dockpipe\` subprocesses and shell — no parallel hidden scheduler outside \`lib/dorkpipe\`."
	echo "- Prefer **templates** and **scripts** for repo-specific glue; keep **lib/dorkpipe** changes general-purpose."
	echo ""

	echo "## 6. Implementation guidance"
	echo "1. Extend \`spec.example.yaml\` in small steps (verifier OR branch OR \`retrieve_if\` — not all at once if it complicates ops)."
	echo "2. Add or adjust tests in \`lib/dorkpipe/*/..._test.go\` when touching aggregation, planner, or workers."
	echo "3. Keep \`dorkpipe validate\` / \`go test ./...\` green."
	echo "4. Document the new path in \`.staging/workflows/dorkpipe-self-analysis/README.md\` and \`docs/dorkpipe.md\` if behavior is user-visible."
	echo ""

	echo "## 7. Acceptance criteria"
	echo "- [ ] \`make build\` and \`go test ./...\` pass."
	echo "- [ ] \`bin/dorkpipe validate -f .staging/workflows/dorkpipe-self-analysis/spec.yaml\` passes."
	echo "- [ ] Running \`dockpipe --workflow dorkpipe-self-analysis --workdir <repo> --\` writes \`.dockpipe/orchestrator-cursor-prompt.md\`."
	echo "- [ ] The handoff references **real** paths present in this repo (verify sections 2–4 against your checkout)."
	echo ""

	echo "## 8. Suggested phased order"
	echo "1. **Instrument**: ensure metrics + eval are part of your local/CI habit."
	echo "2. **Verifier path**: add \`verifier\` node to orchestrator spec; confirm \`run.json\` shows verifier dimension."
	echo "3. **Branch / conditional**: port one pattern from \`lib/dorkpipe/examples/full-bar.yaml\` into a non-demo workflow."
	echo "4. **Promotion**: act on \`dorkpipe promote\` suggestions or tune thresholds when noise is high."
	echo ""
	echo "## 9. Single prompt for your AI assistant"
	echo "The **plain, copy-paste-ready** implementation prompt (no extra narrative) is in **\`.dockpipe/paste-this-prompt.txt\`**. Running \`src/scripts/dorkpipe/run-self-analysis.sh\` **prints that file to stdout** at the end. With \`spec.combined.yaml\`, Ollama output is merged into the same file after the base prompt."
	echo ""
	echo "---"
	echo "_Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)_ · _Facts under \`.dockpipe/self-analysis/\`_"
} >"$DEST"

# Optional Ollama appendix (facts-grounded; set DORKPIPE_SELF_ANALYSIS_USE_OLLAMA=1)
if [[ "${DORKPIPE_SELF_ANALYSIS_USE_OLLAMA:-}" == "1" ]] && command -v python3 >/dev/null 2>&1; then
	HOST="${OLLAMA_HOST:-http://127.0.0.1:11434}"
	MODEL="${DORKPIPE_SELF_ANALYSIS_MODEL:-llama3.2}"
	python3 - "$HOST" "$MODEL" "$OUT" "$DEST" <<'PY' || true
import json, sys, urllib.request, pathlib
host, model, outdir, dest = sys.argv[1:5]
facts = ""
for p in sorted(pathlib.Path(outdir).glob("*.txt")):
    try:
        facts += p.read_text(errors="replace")[:4000] + "\n"
    except OSError:
        pass
facts = facts[:16000]
prompt = (
    "You are a principal engineer. Using ONLY these repository facts, "
    "write markdown with exactly: ## LLM supplement (5 bullets)\n"
    "Each bullet must name a file path from the facts. No generic advice.\n\nFacts:\n" + facts
)
body = json.dumps({"model": model, "prompt": prompt, "stream": False}).encode()
req = urllib.request.Request(host.rstrip("/") + "/api/generate", data=body, headers={"Content-Type": "application/json"})
try:
    with urllib.request.urlopen(req, timeout=120) as r:
        raw = json.loads(r.read().decode())
    text = raw.get("response", str(raw))
    with open(dest, "a", encoding="utf-8") as f:
        f.write("\n\n## LLM supplement (optional)\n\n")
        f.write(text.strip() + "\n")
except Exception as e:
    sys.stderr.write("build-cursor-handoff: Ollama appendix skipped: %s\n" % e)
PY
fi

echo "build-cursor-handoff: wrote $DEST"
wc -c "$DEST" | awk '{print "build-cursor-handoff: bytes", $1}'

# Single copy-paste prompt for an AI assistant (plain text; see below).
PASTE="${ROOT}/.dockpipe/paste-this-prompt.txt"
HEAD_SHA=$(git -C "$ROOT" rev-parse HEAD 2>/dev/null || echo "unknown")
HEAD_REF=$(git -C "$ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
{
	cat <<EOF
You are working in the DockPipe repository. Follow AGENTS.md: DockPipe stays the primitive; DorkPipe (src/lib/dorkpipe/, src/bin/dorkpipe) is orchestration on top — no second hidden engine.

Repository snapshot (machine-generated):
- ref: ${HEAD_REF}
- HEAD: ${HEAD_SHA}
- src/lib/dorkpipe Go files: ${GO_N}

Task: Implement the next concrete improvements to DorkPipe orchestration (multi-signal confidence, conditional nodes, verifiers, eval/promotion) without unnecessary DockPipe core changes.

Do this work in order:
1) If this is a first pass: read src/lib/dorkpipe/engine/run.go and src/lib/dorkpipe/spec/spec.go to see current policy and scheduling.
2) Add or extend a shipped DAG spec (.staging/workflows/dorkpipe-orchestrator/spec.example.yaml) so dogfood matches engine capabilities (e.g. kind: verifier after local LLM, or one pattern from src/lib/dorkpipe/examples/full-bar.yaml).
3) Add tests under src/lib/dorkpipe/*/ when you change aggregation, planner, or workers.
4) Run: make build && go test ./... && src/bin/dorkpipe validate -f .staging/workflows/dorkpipe-self-analysis/spec.yaml

Constraints:
- No vendor-specific hooks in src/lib/dockpipe/application for this work.
- Keep changes general; extend templates/scripts for repo-specific glue.
- Do not fabricate file paths — use paths that exist in this repo.

EOF
	if [[ "$HAS_VERIFIER" -eq 0 ]]; then
		echo "Priority: orchestrator spec.example.yaml still lacks a kind: verifier node after local_reason — add one so Vector.Verifier is populated before escalation (src/lib/dorkpipe/workers/workers.go)."
		echo ""
	fi
	cat <<'EOF'
Start here (files):
- src/lib/dorkpipe/engine/run.go
- src/lib/dorkpipe/workers/workers.go
- src/lib/dorkpipe/aggregator/merge.go
- .staging/workflows/dorkpipe-orchestrator/spec.example.yaml
- src/lib/dorkpipe/examples/full-bar.yaml

Acceptance:
- make build passes; go test ./... passes; dorkpipe validate passes for the YAML you touched.
EOF
} >"$PASTE"
echo "build-cursor-handoff: wrote $PASTE"
