package pipelang

import (
	"strings"
	"testing"
)

func TestCompileGolden(t *testing.T) {
	out, err := Compile([]byte(sampleProgram), "DefaultDeployConfig")
	if err != nil {
		t.Fatalf("compile: %v", err)
	}
	wantYAMLContains := []string{
		"name: defaultdeployconfig",
		"description: Generated by PipeLang v0.0.0.1",
		"IMAGE: nginx",
		`REPLICAS: "1"`,
		`PUBLIC: "false"`,
	}
	gotYAML := string(out.WorkflowYAML)
	for _, w := range wantYAMLContains {
		if !strings.Contains(gotYAML, w) {
			t.Fatalf("workflow yaml missing %q:\n%s", w, gotYAML)
		}
	}
	gotJSON := string(out.BindingsJSON)
	if !strings.Contains(gotJSON, `"entry_class": "DefaultDeployConfig"`) {
		t.Fatalf("bindings json missing entry class:\n%s", gotJSON)
	}
	if !strings.Contains(gotJSON, `"name": "FullImage"`) {
		t.Fatalf("bindings json missing method metadata:\n%s", gotJSON)
	}
	if strings.Contains(gotJSON, `"name": "IsTiny"`) {
		t.Fatalf("bindings json should not expose private method:\n%s", gotJSON)
	}
	gotEnv := string(out.BindingsEnv)
	if !strings.Contains(gotEnv, "PIPELANG_IMAGE='nginx'") {
		t.Fatalf("bindings env missing IMAGE:\n%s", gotEnv)
	}
	if strings.Contains(gotEnv, "PIPELANG_INTERNAL_SUFFIX") {
		t.Fatalf("bindings env should not expose private field:\n%s", gotEnv)
	}
}
