package pipelang

import (
	"strings"
	"testing"
)

func TestCompileGolden(t *testing.T) {
	out, err := Compile([]byte(sampleProgram), "DefaultDeployConfig")
	if err != nil {
		t.Fatalf("compile: %v", err)
	}
	wantYAMLContains := []string{
		"name: defaultdeployconfig",
		"description: Generated by PipeLang v0.0.0.1",
		"IMAGE: nginx",
		`REPLICAS: "1"`,
		`PUBLIC: "false"`,
	}
	gotYAML := string(out.WorkflowYAML)
	for _, w := range wantYAMLContains {
		if !strings.Contains(gotYAML, w) {
			t.Fatalf("workflow yaml missing %q:\n%s", w, gotYAML)
		}
	}
	gotJSON := string(out.BindingsJSON)
	if !strings.Contains(gotJSON, `"entry_class": "DefaultDeployConfig"`) {
		t.Fatalf("bindings json missing entry class:\n%s", gotJSON)
	}
	if !strings.Contains(gotJSON, `"name": "FullImage"`) {
		t.Fatalf("bindings json missing method metadata:\n%s", gotJSON)
	}
	if strings.Contains(gotJSON, `"name": "IsTiny"`) {
		t.Fatalf("bindings json should not expose private method:\n%s", gotJSON)
	}
	gotEnv := string(out.BindingsEnv)
	if !strings.Contains(gotEnv, "PIPELANG_IMAGE='nginx'") {
		t.Fatalf("bindings env missing IMAGE:\n%s", gotEnv)
	}
	if strings.Contains(gotEnv, "PIPELANG_INTERNAL_SUFFIX") {
		t.Fatalf("bindings env should not expose private field:\n%s", gotEnv)
	}
}

func TestCompileMapsPascalCaseFieldsToWorkflowBindings(t *testing.T) {
	src := `public Interface IR2
{
    public string DockpipeTfBackend;
    public string TfVarPublicHostname;
    public string R2Bucket;
}

public Class R2Config : IR2
{
    public string DockpipeTfBackend = "remote";
    public string TfVarPublicHostname = "packages.example.com";
    public string R2Bucket = "dockpipe";
}
`
	out, err := Compile([]byte(src), "R2Config")
	if err != nil {
		t.Fatalf("compile: %v", err)
	}
	gotYAML := string(out.WorkflowYAML)
	for _, want := range []string{
		"DOCKPIPE_TF_BACKEND: remote",
		"TF_VAR_public_hostname: packages.example.com",
		"R2_BUCKET: dockpipe",
	} {
		if !strings.Contains(gotYAML, want) {
			t.Fatalf("workflow yaml missing %q:\n%s", want, gotYAML)
		}
	}
	gotEnv := string(out.BindingsEnv)
	for _, want := range []string{
		"PIPELANG_DOCKPIPE_TF_BACKEND='remote'",
		"PIPELANG_TF_VAR_public_hostname='packages.example.com'",
		"PIPELANG_R2_BUCKET='dockpipe'",
	} {
		if !strings.Contains(gotEnv, want) {
			t.Fatalf("bindings env missing %q:\n%s", want, gotEnv)
		}
	}
}
