package handoff

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"dorkpipe.orchestrator/statepaths"
)

type CursorResult struct {
	DocumentPath string
	PastePath    string
	Bytes        int
}

func BuildCursor(workdir string, env map[string]string) (CursorResult, error) {
	root, err := filepath.Abs(workdir)
	if err != nil {
		return CursorResult{}, err
	}
	out, err := statepaths.SelfAnalysisDir(root)
	if err != nil {
		return CursorResult{}, err
	}
	dest := statepaths.CursorPromptPath(root)
	paste := statepaths.PastePromptPath(root)
	if fi, err := os.Stat(out); err != nil || !fi.IsDir() {
		return CursorResult{}, fmt.Errorf("build-cursor-handoff: missing %s — run self-analysis-prep.sh and self-analysis-signals.sh first", out)
	}
	if err := os.MkdirAll(filepath.Join(root, "bin", ".dockpipe"), 0o755); err != nil {
		return CursorResult{}, err
	}

	goCount := readTrimmed(filepath.Join(out, "dorkpipe_go_files.count"), "0")
	spec := filepath.Join(root, "packages", "dorkpipe", "resolvers", "dorkpipe-orchestrator", "spec.example.yaml")
	hasVerifier := fileContains(spec, "kind: verifier")
	_ = fileExists(filepath.Join(root, "packages", "dorkpipe", "lib", "examples", "full-bar.yaml"))

	var doc strings.Builder
	doc.WriteString("# Cursor implementation handoff — DockPipe + DorkPipe orchestration\n\n")
	doc.WriteString("This document was generated by **DockPipe’s self-analysis workflow** from **real repository scans** (file lists, ripgrep/grep hits, git metadata). Treat unchecked items as hypotheses to validate in code review.\n\n")
	doc.WriteString("## 1. Objective\n")
	doc.WriteString("Advance **DockPipe** (workflow execution fabric) and **DorkPipe** (`lib/dorkpipe/`, `bin/dorkpipe`) toward stronger **orchestrated reasoning**: multi-signal confidence, conditional retrieval/work, independent verifiers, bounded branch competition, evaluation (`dorkpipe eval`), and promotion of reusable assets — **without** replacing DockPipe’s core primitive or inventing a second engine.\n\n")
	doc.WriteString("## 2. Current state summary (from this checkout)\n")
	doc.WriteString(fmt.Sprintf("- **Go files in `lib/dorkpipe`**: %s\n", goCount))
	doc.WriteString("- **Git HEAD / branch** (see `bin/.dockpipe/packages/dorkpipe/self-analysis/git.txt` for full):\n")
	for _, line := range headLines(filepath.Join(out, "git.txt"), 3) {
		doc.WriteString("  " + line + "\n")
	}
	doc.WriteString("- **DorkPipe packages (file counts)**:\n")
	for _, line := range fileLines(filepath.Join(out, "dorkpipe_packages.tsv")) {
		doc.WriteString("  " + line + "\n")
	}
	doc.WriteString("- **Workflow configs present**:\n")
	for _, line := range fileLines(filepath.Join(out, "workflow_configs.txt")) {
		doc.WriteString("  " + line + "\n")
	}
	doc.WriteString("- **Recent commits**:\n")
	for _, line := range fileLines(filepath.Join(out, "signals_git_log.txt")) {
		doc.WriteString("  " + line + "\n")
	}
	doc.WriteString("\n## 3. Highest-value opportunities (grounded + strategic)\n")
	doc.WriteString("The following are **actionable** directions consistent with `AGENTS.md` (primitive core, templates as extension):\n\n")
	if !hasVerifier {
		doc.WriteString("- **Independent verifier in the default orchestrator spec** (`packages/dorkpipe/resolvers/dorkpipe-orchestrator/spec.example.yaml`): add a `kind: verifier` node after local LLM output so `Vector.Verifier` is populated before escalation (implementation in `lib/dorkpipe/workers/workers.go`, `parseVerifierScore`).\n")
	}
	doc.WriteString("- **Surface engine features in shipped examples**: `lib/dorkpipe/examples/full-bar.yaml` demonstrates `branch_judge`, `retrieve_if_calibrated_below`, and skips — mirror one pattern into `spec.example.yaml` so dogfood exercises the same code paths operators will rely on.\n")
	doc.WriteString("- **Metrics loop**: standardize `bin/dorkpipe eval` / `promote` after CI or nightly runs; extend `bin/.dockpipe/packages/dorkpipe/metrics.jsonl` consumers if new dimensions are added (`lib/dorkpipe/engine/provenance.go`).\n")
	doc.WriteString("- **Asset promotion**: scripts under `templates/core/bundles/dorkpipe/` should stay referenced from workflows/docs when they become part of a supported path (collect/merge/verify-*).\n")
	doc.WriteString("- **TODO/FIXME triage**: review hits in `bin/.dockpipe/packages/dorkpipe/self-analysis/signals_todo.txt`; convert stable items into issues or small PRs.\n")
	if fileExists(filepath.Join(root, "bin", ".dockpipe", "packages", "dorkpipe", "metrics.jsonl")) && fileExists(filepath.Join(out, "signals_metrics_tail.txt")) {
		doc.WriteString("- **Existing `bin/.dockpipe/packages/dorkpipe/metrics.jsonl`**: tail captured in `bin/.dockpipe/packages/dorkpipe/self-analysis/signals_metrics_tail.txt` — use for escalation / early-stop rates.\n")
	}
	doc.WriteString("\n### Search hits (files touching orchestration keywords)\n")
	for _, line := range fileLines(filepath.Join(out, "signals_engine_files.txt")) {
		doc.WriteString("  " + line + "\n")
	}
	doc.WriteString("\n## 4. Exact files/modules to inspect\n")
	doc.WriteString("| Area | Path |\n|------|------|\n")
	doc.WriteString("| Engine / run loop | `lib/dorkpipe/engine/run.go`, `lib/dorkpipe/engine/provenance.go`, `lib/dorkpipe/engine/branch.go`, `lib/dorkpipe/engine/parallel.go` |\n")
	doc.WriteString("| Spec / policy | `lib/dorkpipe/spec/spec.go` |\n")
	doc.WriteString("| Workers | `lib/dorkpipe/workers/workers.go` |\n")
	doc.WriteString("| Aggregation | `lib/dorkpipe/aggregator/merge.go` |\n")
	doc.WriteString("| CLI | `packages/dorkpipe/lib/cmd/dorkpipe/main.go` |\n")
	doc.WriteString("| Eval / promotion | `lib/dorkpipe/eval/eval.go`, `lib/dorkpipe/promotion/promotion.go` |\n")
	doc.WriteString("| DockPipe workflow (this integration) | `packages/dorkpipe/resolvers/dorkpipe-self-analysis/` |\n")
	doc.WriteString("| Orchestrator example DAG | `packages/dorkpipe/resolvers/dorkpipe-orchestrator/spec.example.yaml` |\n\n")
	if lines := fileLines(filepath.Join(out, "key_file_wc.txt")); len(lines) > 0 {
		doc.WriteString("### Line counts (signal for complexity hotspots)\n")
		for _, line := range lines {
			doc.WriteString("  " + line + "\n")
		}
		doc.WriteString("\n")
	}
	doc.WriteString("## 5. Constraints / architecture rules (non-negotiable)\n")
	doc.WriteString("- **DockPipe core** stays the single execution fabric: workflows, runtimes, resolvers, strategies, assets (`AGENTS.md`).\n")
	doc.WriteString("- **No** vendor-specific logic in `src/lib/application` / runner for this work.\n")
	doc.WriteString("- **DorkPipe** composes via real `dockpipe` subprocesses and shell — no parallel hidden scheduler outside `lib/dorkpipe`.\n")
	doc.WriteString("- Prefer **templates** and **scripts** for repo-specific glue; keep **lib/dorkpipe** changes general-purpose.\n\n")
	doc.WriteString("## 6. Implementation guidance\n")
	doc.WriteString("1. Extend `spec.example.yaml` in small steps (verifier OR branch OR `retrieve_if` — not all at once if it complicates ops).\n")
	doc.WriteString("2. Add or adjust tests in `lib/dorkpipe/*/..._test.go` when touching aggregation, planner, or workers.\n")
	doc.WriteString("3. Keep `dorkpipe validate` / `go test ./...` green.\n")
	doc.WriteString("4. Document the new path in `packages/dorkpipe/resolvers/dorkpipe-self-analysis/README.md` if behavior is user-visible.\n\n")
	doc.WriteString("## 7. Acceptance criteria\n")
	doc.WriteString("- [ ] `make build` and `go test ./...` pass.\n")
	doc.WriteString("- [ ] `bin/dorkpipe validate -f packages/dorkpipe/resolvers/dorkpipe-self-analysis/spec.yaml` passes.\n")
	doc.WriteString("- [ ] Running `dockpipe --workflow dorkpipe-self-analysis --workdir <repo> --` writes `bin/.dockpipe/orchestrator-cursor-prompt.md`.\n")
	doc.WriteString("- [ ] The handoff references **real** paths present in this repo (verify sections 2–4 against your checkout).\n\n")
	doc.WriteString("## 8. Suggested phased order\n")
	doc.WriteString("1. **Instrument**: ensure metrics + eval are part of your local/CI habit.\n")
	doc.WriteString("2. **Verifier path**: add `verifier` node to orchestrator spec; confirm `run.json` shows verifier dimension.\n")
	doc.WriteString("3. **Branch / conditional**: port one pattern from `lib/dorkpipe/examples/full-bar.yaml` into a non-demo workflow.\n")
	doc.WriteString("4. **Promotion**: act on `dorkpipe promote` suggestions or tune thresholds when noise is high.\n\n")
	doc.WriteString("## 9. Single prompt for your AI assistant\n")
	doc.WriteString("The **plain, copy-paste-ready** implementation prompt (no extra narrative) is in **`bin/.dockpipe/paste-this-prompt.txt`**. Running `./packages/dorkpipe/resolvers/dorkpipe/assets/scripts/run-self-analysis.sh` **prints that file to stdout** at the end. With `spec.combined.yaml`, Ollama output is merged into the same file after the base prompt.\n\n---\n")
	doc.WriteString(fmt.Sprintf("_Generated: %s_ · _Facts under `bin/.dockpipe/packages/dorkpipe/self-analysis/`_\n", time.Now().UTC().Format(time.RFC3339)))

	if err := os.WriteFile(dest, []byte(doc.String()), 0o644); err != nil {
		return CursorResult{}, err
	}
	if env["DORKPIPE_SELF_ANALYSIS_USE_OLLAMA"] == "1" {
		if err := maybeAppendOllama(env, out, dest); err != nil {
			fmt.Fprintf(os.Stderr, "build-cursor-handoff: Ollama appendix skipped: %v\n", err)
		}
	}
	pasteBody := buildPastePrompt(root, goCount, hasVerifier)
	if err := os.WriteFile(paste, []byte(pasteBody), 0o644); err != nil {
		return CursorResult{}, err
	}
	info, err := os.Stat(dest)
	if err != nil {
		return CursorResult{}, err
	}
	return CursorResult{DocumentPath: dest, PastePath: paste, Bytes: int(info.Size())}, nil
}

func buildPastePrompt(root, goCount string, hasVerifier bool) string {
	headSHA := gitOutput(root, "rev-parse", "HEAD")
	if headSHA == "" {
		headSHA = "unknown"
	}
	headRef := gitOutput(root, "rev-parse", "--abbrev-ref", "HEAD")
	if headRef == "" {
		headRef = "unknown"
	}
	var b strings.Builder
	b.WriteString("You are working in the DockPipe repository. Follow AGENTS.md: DockPipe stays the primitive; DorkPipe (packages/dorkpipe/lib/, dorkpipe/bin/dorkpipe) is orchestration on top — no second hidden engine.\n\n")
	b.WriteString("Repository snapshot (machine-generated):\n")
	b.WriteString(fmt.Sprintf("- ref: %s\n", headRef))
	b.WriteString(fmt.Sprintf("- HEAD: %s\n", headSHA))
	b.WriteString(fmt.Sprintf("- dorkpipe.orchestrator Go files: %s\n\n", goCount))
	b.WriteString("Task: Implement the next concrete improvements to DorkPipe orchestration (multi-signal confidence, conditional nodes, verifiers, eval/promotion) without unnecessary DockPipe core changes.\n\n")
	b.WriteString("Do this work in order:\n")
	b.WriteString("1) If this is a first pass: read packages/dorkpipe/lib/engine/run.go and packages/dorkpipe/lib/spec/spec.go to see current policy and scheduling.\n")
	b.WriteString("2) Add or extend a shipped DAG spec (packages/dorkpipe/resolvers/dorkpipe-orchestrator/spec.example.yaml) so dogfood matches engine capabilities (e.g. kind: verifier after local_reason, or one pattern from packages/dorkpipe/lib/examples/full-bar.yaml).\n")
	b.WriteString("3) Add tests under packages/dorkpipe/lib/*/ when you change aggregation, planner, or workers.\n")
	b.WriteString("4) Run: make build && go test ./... && packages/dorkpipe/bin/dorkpipe validate -f packages/dorkpipe/resolvers/dorkpipe-self-analysis/spec.yaml\n\n")
	b.WriteString("Constraints:\n")
	b.WriteString("- No vendor-specific hooks in src/lib/application for this work.\n")
	b.WriteString("- Keep changes general; extend templates/scripts for repo-specific glue.\n")
	b.WriteString("- Do not fabricate file paths — use paths that exist in this repo.\n\n")
	if !hasVerifier {
		b.WriteString("Priority: orchestrator spec.example.yaml still lacks a kind: verifier node after local_reason — add one so Vector.Verifier is populated before escalation (packages/dorkpipe/lib/workers/workers.go).\n\n")
	}
	b.WriteString("Start here (files):\n")
	b.WriteString("- packages/dorkpipe/lib/engine/run.go\n")
	b.WriteString("- packages/dorkpipe/lib/workers/workers.go\n")
	b.WriteString("- packages/dorkpipe/lib/aggregator/merge.go\n")
	b.WriteString("- packages/dorkpipe/resolvers/dorkpipe-orchestrator/spec.example.yaml\n")
	b.WriteString("- packages/dorkpipe/lib/examples/full-bar.yaml\n\n")
	b.WriteString("Acceptance:\n")
	b.WriteString("- make build passes; go test ./... passes; dorkpipe validate passes for the YAML you touched.\n")
	return b.String()
}

func maybeAppendOllama(env map[string]string, outdir, dest string) error {
	host := env["OLLAMA_HOST"]
	if host == "" {
		host = "http://127.0.0.1:11434"
	}
	model := env["DORKPIPE_SELF_ANALYSIS_MODEL"]
	if model == "" {
		model = "llama3.2"
	}
	facts := collectFacts(outdir)
	payload := map[string]any{
		"model":  model,
		"prompt": "You are a principal engineer. Using ONLY these repository facts, write markdown with exactly: ## LLM supplement (5 bullets)\nEach bullet must name a file path from the facts. No generic advice.\n\nFacts:\n" + facts,
		"stream": false,
	}
	body, err := json.Marshal(payload)
	if err != nil {
		return err
	}
	resp, err := http.Post(strings.TrimRight(host, "/")+"/api/generate", "application/json", bytes.NewReader(body))
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	raw, err := io.ReadAll(io.LimitReader(resp.Body, 2<<20))
	if err != nil {
		return err
	}
	var decoded struct {
		Response string `json:"response"`
	}
	if err := json.Unmarshal(raw, &decoded); err != nil {
		return err
	}
	f, err := os.OpenFile(dest, os.O_APPEND|os.O_WRONLY, 0o644)
	if err != nil {
		return err
	}
	defer f.Close()
	_, err = fmt.Fprintf(f, "\n\n## LLM supplement (optional)\n\n%s\n", strings.TrimSpace(decoded.Response))
	return err
}

func collectFacts(outdir string) string {
	var b strings.Builder
	entries, _ := os.ReadDir(outdir)
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".txt") {
			continue
		}
		body, err := os.ReadFile(filepath.Join(outdir, entry.Name()))
		if err != nil {
			continue
		}
		b.Write(body[:min(len(body), 4000)])
		b.WriteString("\n")
		if b.Len() >= 16000 {
			return b.String()[:16000]
		}
	}
	return b.String()
}

func headLines(path string, n int) []string {
	lines := fileLines(path)
	if len(lines) > n {
		return lines[:n]
	}
	return lines
}

func fileLines(path string) []string {
	body, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	lines := strings.Split(strings.ReplaceAll(string(body), "\r\n", "\n"), "\n")
	out := make([]string, 0, len(lines))
	for _, line := range lines {
		if strings.TrimSpace(line) != "" {
			out = append(out, line)
		}
	}
	return out
}

func readTrimmed(path, fallback string) string {
	body, err := os.ReadFile(path)
	if err != nil {
		return fallback
	}
	v := strings.TrimSpace(string(body))
	if v == "" {
		return fallback
	}
	return v
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func fileContains(path, want string) bool {
	body, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return strings.Contains(string(body), want)
}

func gitOutput(root string, args ...string) string {
	cmd := exec.Command("git", append([]string{"-C", root}, args...)...)
	out, err := cmd.Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
