#!/usr/bin/env bash
# Host prep: Cursor desktop hints + AI agent / MCP quickstart (no remote Cursor server).
set -euo pipefail

ROOT="$(dockpipe get workdir)"
STATE_ROOT="${DOCKPIPE_PACKAGE_STATE_DIR:-${DOCKPIPE_STATE_DIR:-$ROOT/bin/.dockpipe}/packages/cursor-dev}"
DIR="$STATE_ROOT"
mkdir -p "$DIR"

# Dockpipe source checkout (src/cmd/mcpd) — after `make build`, binaries exist under src/bin/.
HAS_MCP=""
if [[ -f "$ROOT/src/bin/mcpd" ]] || [[ -f "$ROOT/src/cmd/mcpd/main.go" ]]; then
  HAS_MCP=1
fi

cat > "$DIR/README.txt" <<EOF
cursor-dev (Dockpipe)

Project root (host): ${ROOT}

This folder is written by the cursor-dev resolver for any workflow that runs cursor-prep
(experimental Cursor + Docker session, AI agent hints).

Dockpipe does not install a "Cursor server". Use the Cursor desktop app and open this folder.

Container sessions mount this directory at /work when you use cursor-dev with Docker.

For AI assistants and MCP setup, read: ${DIR}/AGENT-MCP.md
EOF

cat > "$DIR/AGENT-MCP.md" <<EOF
# Cursor + DockPipe — AI agent and MCP

**This project root:** \`${ROOT}\`

This file is generated by **cursor-dev** so agents and humans share the same facts: where the repo lives, how DockPipe/MCP relate, and what to configure in Cursor.

## What cursor-dev does here

- **Host:** open this folder in Cursor (File → Open Folder). Your tree is the source of truth.
- **Containers:** when you run \`dockpipe\` with the cursor-dev resolver and Docker, this directory is typically mounted at \`/work\` inside the session container.
- **\`DOCKPIPE_WORKDIR\`:** should point at the project you want DockPipe and Cursor to operate on. For work in this tree, use: \`${ROOT}\`.

## MCP (Model Context Protocol) — \`mcpd\`

DockPipe ships **\`mcpd\`**, a small bridge that exposes **named tools** (workflow list, validate YAML, CLI version, …) to Cursor over stdio or HTTPS. See **\`docs/mcp-agent-trust.md\`** (in the dockpipe repo) for tiers and trust.

### If this checkout is the **dockpipe** repository

1. From the repo root: \`make build\` then \`make maintainer-tools\`.
   That gives you \`src/bin/dockpipe\`, \`packages/dorkpipe/bin/dorkpipe\`, and \`packages/dorkpipe/bin/mcpd\`.
2. In Cursor: enable **MCP** and use the project file **\`.cursor/mcp.json\`** at the repo root (or merge **\`bin/.dockpipe/packages/cursor-dev/mcp.json.example\`** from this folder if present).
3. Restart Cursor after editing MCP config.
4. Defaults are security-first (workdir under repo, absolute paths to CLIs) — see **\`docs/mcp-host-hardening.md\`**.

### If this is an **application** project (DockPipe installed system-wide)

Point MCP \`command\` at your \`mcpd\` binary. Set \`DOCKPIPE_BIN\` and \`DORKPIPE_BIN\` in the MCP server \`env\` to **absolute** paths to the \`dockpipe\` and \`dorkpipe\` executables (defaults require this).

## Where to read more (dockpipe repo)

| Doc | Topic |
|-----|--------|
| \`docs/mcp-agent-trust.md\` | Tiers, artifacts vs tools |
| \`docs/mcp-host-hardening.md\` | Host / PATH / workdir knobs |
| \`src/lib/mcpbridge/README.md\` | Env vars, HTTP mode |
| \`AGENTS.md\` | Maintainer contract for this repository |

EOF

if [[ -n "$HAS_MCP" ]]; then
  cat > "$DIR/mcp.json.example" <<JSON
{
  "mcpServers": {
    "dockpipe": {
      "command": "${ROOT}/packages/dorkpipe/bin/mcpd",
      "args": [],
      "env": {
        "DOCKPIPE_BIN": "${ROOT}/src/bin/dockpipe",
        "DORKPIPE_BIN": "${ROOT}/packages/dorkpipe/bin/dorkpipe"
      }
    }
  }
}
JSON
else
  cat > "$DIR/mcp.json.example" <<'JSON'
{
  "mcpServers": {
    "dockpipe": {
      "command": "mcpd",
      "args": [],
      "env": {
        "DOCKPIPE_BIN": "/absolute/path/to/dockpipe",
        "DORKPIPE_BIN": "/absolute/path/to/dorkpipe"
      }
    }
  }
}
JSON
fi

printf '[dockpipe] Wrote %s (AI agent + MCP: %s)\n' "$DIR/README.txt" "$DIR/AGENT-MCP.md" >&2
if [[ -f "$DIR/mcp.json.example" ]]; then
  printf '[dockpipe] Wrote %s\n' "$DIR/mcp.json.example" >&2
fi
